server:
    port: 8080

spring:
    application:
        name: gateway

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  ConnectTimeout: 5000
  ReadTimeout: 5000
  ServerListRefreshInterval: 5000 
  eureka:
    enabled: true

eureka:
    client:
        registryFetchIntervalSeconds : 30

hystrix:
    command:
        default:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 8000

zuul:
    host:
        max-total-connections: 60000
        max-per-route-connections: 60000
    semaphore:
        max-semaphores: 500
    ignoredServices: "*"
    routes:
        ecommerce: 
            path: /ecommerce/**
            serviceId: ecommerce

        stock: 
            path: /estoque/**
            serviceId: estoque